version: 2.1

parameters:
  root-folder:
    type: string
    default: ~/github.com/personal/circleci
  frontend-folder:
    type: string
    default: << pipeline.parameters.root-folder >>/frontend
  frontend-has-changed:
    type: boolean
    default: false

executors:
  node_executor:
    docker:
      - image: cimg/node:18

jobs:
  checkout:
    executor: node_executor
    working_directory: << pipeline.parameters.frontend-folder >>
    steps:
      - checkout:
          path: << pipeline.parameters.root-folder >>
      - restore_cache:
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run: curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm@7
      - run: pnpm install
      - save_cache:
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: << pipeline.parameters.frontend-folder >>
          paths:
            - ./*

  build:
    executor: node_executor
    working_directory: << pipeline.parameters.frontend-folder >>
    steps:
      - attach_workspace:
          at: << pipeline.parameters.frontend-folder >>
      - run: npm run build
      
  test:
    executor: node_executor
    working_directory: << pipeline.parameters.frontend-folder >>
    steps:
      - attach_workspace:
          at: << pipeline.parameters.frontend-folder >>
      - run: npm run test
  
  deploy:
    executor: node_executor
    working_directory: << pipeline.parameters.frontend-folder >>
    steps:
      - attach_workspace:
          at: << pipeline.parameters.frontend-folder >>

workflows:
  on_commit:
    when: << pipeline.parameters.frontend-has-changed >>
    jobs:
      - checkout
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main