version: 2.1
setup: true

parameters:
  backend-has-changed:
    type: boolean
    default: false

jobs:
  build:
    docker:
      - image: cimg/go:1.19.1
    steps:
      - checkout
      - run: go install
      - run: go build
      - run: go test -v

workflows:
  on_commit:
    when: << pipeline.parameters.backend-has-changed >>
    jobs:
      - build